### ISSUE TITLE
Bug : "Start the Journey" button is taking 2-3 seconds to load 

### ISSUE THREAD

**Issue by RomeoIndiaJulietUniform** [RomeoIndiaJulietUniform/3Dportfoliowebsite-#1]
# Steps to reproduce:
Upon loaing the screen , the "Start the Journey" button is taking 2-3 secs to become clickable, the issue arises after the Ending Overlay feature is pushed 

![Screenshot from 2024-10-14 20-21-32](https://github.com/user-attachments/assets/3fe859d9-e1fb-4ab2-994c-922b88e904c8)

**Comment by YuvamGupta** [comment]
The bug is due to the animation property on the scroll class in `src/components/Overlay.jsx`. The animation is 7 seconds and it takes the button 7 seconds to become interactive.

**Comment by RomeoIndiaJulietUniform** [comment]
Hii @YuvamGupta , great catch!  want to raise a PR for this if you are comfortable?

**Comment by YuvamGupta** [comment]
@RomeoIndiaJulietUniform I am currently working on alternatives to the problem. As soon as I am done I'll merge the request

**Comment by YuvamGupta** [comment]
@RomeoIndiaJulietUniform Please merge the pull request and kindly add the hacktoberfest topic to this repo. Thanks
Link to [Guide for maintainers](https://hacktoberfest.com/participation/#maintainers).
